language: python
python:
- 3.4
install:
- pip install -r scripts/requirements-test.txt
script:
- goodtables datapackage datapackage.json
notifications:
  email: false
  slack:
    on_success: change
    rooms:
      # civictechto:<token>#open-data
    - secure: Bh4L3Oyp3SoPHq3mivA/oZT5p4w51DveMwoupRasHTAOEvtfqpHfZQ/hgw4Y6jHJJrDyjVZ9YJ7d7lE6dxYuPOOWIMWTjNmyb6WYQHfKj3DxzgWcnsMxbatKI2De2s6K2aFkSIe4eFNbRggsl1cSFzFlrC8zQ6AItiyHH8mBGzNc7BgOFJwyuC9nKh0eFSEiYe9bupx2z6nytoJfj0OvXzfOv6WHb3LVKmpOvSwU3W8iwfiuGL9GubloTPw5/E2wr7WFxGp7j7GA43c23CO5n1Xf4tmuRUVCILObsYo8mkFhwGDZieWmKbvMn1wD5CxX7FMRD8zx+bSs5dHf8cb0sqsRJHU7mfTIvq+FOIm9OLu+apLD/TcWuhzoSCfMGuyb9OkBIKdd7OxPLLBgg3rmnG61jNlKbAfjmtWxlCiAgUAUd2hixk2XEbIInF1aZRJV1styiu5PdOVJdpmvs8e4qh9q7N0ljW9VAmM/wY+7IliuXBW33hUj32SMdKYj7rkBIQvS4zA0+GJyv3uElDkV82r2GPtdtBcep3PYWY+kAm9OiZSG8XbplUhT5fWJi3MsaiWLKvkWBQ1Svx22cs2KmiTFw3QkYD3XfNjyWOkpmKVDeRXq0oR/pBRMFKHPQOrOw2q0Bp8bsjulU8k5lHA68XpgjYIhKKIzFex0D3DywBI=
